// ─────────────────────────────────────────────────────────────────────────────
// Golden-frame fixture PROJECTS (Spec §22.3 / §22.6).
//
// Three minimal §18 `Project` documents, each exercising ONE high-risk graph path
// of buildExportCommand so a golden-frame SSIM/PSNR breach localises to a single
// behaviour:
//
//   (a) "trim"   — per-clip -ss/-to accurate seek from the SOURCE origin (§3.8).
//   (b) "stack"  — multi-track composite + overlay z-order: track 0 (bottom) is
//                  covered by a smaller PiP clip on track 1 (top) (§18.3 z-order).
//   (c) "speed"  — per-clip setpts speed change (2×) (§3.3, §5.1).
//
// Each project references SYNTHETIC fixture media generated by
// scripts/generate-fixtures.ts (lavfi testsrc/colour sources — CC0). The asset ids
// below map to those files via FIXTURE_ASSET_MAP (consumed by golden.test.ts and
// generate-fixtures.ts). All ids are stable UUID-v4 literals so the goldens are
// deterministically tied to a fixed input (the §22.3 precondition).
//
// Geometry is percent (0–100); time is integer ms; track index = z-order. These
// projects are intentionally tiny (single short clips) so a render is sub-second
// and the committed golden PNGs stay small + diff-reviewable (no Git LFS).
// ─────────────────────────────────────────────────────────────────────────────

import type {
  Project,
  VideoTrack,
  Clip,
  OverlayTrack,
  TextOverlay,
  TextStyle,
} from "@videoforge/project-schema";
import type { ExportSettings } from "@videoforge/ffmpeg-graph";

// ── Stable ids ────────────────────────────────────────────────────────────────
const OWNER_ID = "4f3a6c2e-1b8d-4e2a-9c7f-0a1b2c3d4e5f";
const WORKSPACE_ID = "7c9e6679-7425-40de-944b-e07fc1f90ae7";

// Synthetic source assets (mapped to fixture files in FIXTURE_ASSET_MAP).
export const ASSET_BARS = "aa000000-0000-4000-8000-000000000001"; // testsrc2 counter clip
export const ASSET_RED = "aa000000-0000-4000-8000-000000000002"; // solid red clip
export const ASSET_BLUE = "aa000000-0000-4000-8000-000000000003"; // solid blue clip

/**
 * Asset id → synthetic fixture filename (under fixtures/media/). The render
 * harness substitutes `asset:<id>` tokens with these paths; the generator
 * produces exactly these files. Keeping the map here keeps it single-source.
 */
export const FIXTURE_ASSET_MAP: Record<string, string> = {
  [ASSET_BARS]: "gold_bars_5s.mp4",
  [ASSET_RED]: "gold_red_3s.mp4",
  [ASSET_BLUE]: "gold_blue_3s.mp4",
};

// ── Shared export settings (lossy H.264 @ Auto-CRF row of §22.3) ────────────────
// 640×360 keeps goldens tiny; watermark/captions OFF so the gate isolates the
// graph path under test (no font/branding-asset dependence in the golden image).
export const GOLDEN_EXPORT_SETTINGS: ExportSettings = {
  format: "mp4",
  videoCodec: "h264",
  resolution: { w: 640, h: 360 },
  fps: 30,
  crf: 18,
  captions: "none",
  watermark: false,
};

// ── Helpers ─────────────────────────────────────────────────────────────────────
function videoTrack(id: string, name: string, clips: Clip[]): VideoTrack {
  return {
    id,
    type: "video",
    name,
    colour: "#3A6BFF",
    height: 72,
    muted: false,
    solo: false,
    locked: false,
    clips,
  };
}

function baseProject(id: string, title: string, tracks: VideoTrack[]): Project {
  return {
    schemaVersion: 1,
    revision: 1,
    id,
    title,
    description: `Golden-frame fixture: ${title}`,
    canvas: {
      width: 640,
      height: 360,
      frameRate: 30,
      aspectRatio: "16:9",
      backgroundColor: "#000000",
    },
    tracks,
    captionTracks: [],
    transitions: [],
    markers: [],
    exportPresets: [],
    ownerId: OWNER_ID,
    workspaceId: WORKSPACE_ID,
    collaborators: [{ userId: OWNER_ID, role: "admin" }],
    isPublic: false,
    templateId: null,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z",
  };
}

// ── (a) TRIM ─────────────────────────────────────────────────────────────────────
// One clip from the testsrc counter source, trimmed to source 2000–4000ms. The
// extracted golden frame must show the counter/colour state at SOURCE t=2s+, NOT
// t=0 — proving -ss/-to seeks from the source origin, not the timeline.
export const trimProject: Project = baseProject(
  "11111111-1111-4111-8111-111111111111",
  "trim",
  [
    videoTrack("11111111-1111-4111-8111-1111111111a0", "Video 1", [
      {
        id: "11111111-1111-4111-8111-1111111111c0",
        sourceAssetId: ASSET_BARS,
        trackId: "11111111-1111-4111-8111-1111111111a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 2000,
        trimOut: 4000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
  ],
);

// ── (b) STACK / OVERLAY Z-ORDER ──────────────────────────────────────────────────
// Track 0 (bottom) = full-frame RED. Track 1 (top) = a BLUE PiP box covering the
// centre. The golden must show RED background with a BLUE rectangle ON TOP — if the
// overlay z-order inverts, SSIM collapses (blue would be hidden behind red).
export const stackProject: Project = baseProject(
  "22222222-2222-4222-8222-222222222222",
  "stack",
  [
    // index 0 = bottom layer
    videoTrack("22222222-2222-4222-8222-2222222222a0", "Background", [
      {
        id: "22222222-2222-4222-8222-2222222222c0",
        sourceAssetId: ASSET_RED,
        trackId: "22222222-2222-4222-8222-2222222222a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
    // index 1 = top layer — BLUE centred PiP box (40% size, centred).
    videoTrack("22222222-2222-4222-8222-2222222222a1", "PiP", [
      {
        id: "22222222-2222-4222-8222-2222222222c1",
        sourceAssetId: ASSET_BLUE,
        trackId: "22222222-2222-4222-8222-2222222222a1",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
        transform: { x: 30, y: 30, width: 40, height: 40 },
      },
    ]),
  ],
);

// ── (c) SPEED CHANGE ──────────────────────────────────────────────────────────────
// One clip from the testsrc counter source at 2× speed (setpts=0.5*PTS). A 4s source
// span plays in 2s. The frame sampled at timeline t=1.0s must equal the SOURCE state
// at t=2.0s — proving the setpts time-warp. If speed is ignored, the sampled frame
// shows source t=1.0s and SSIM collapses.
export const speedProject: Project = baseProject(
  "33333333-3333-4333-8333-333333333333",
  "speed",
  [
    videoTrack("33333333-3333-4333-8333-3333333333a0", "Video 1", [
      {
        id: "33333333-3333-4333-8333-3333333333c0",
        sourceAssetId: ASSET_BARS,
        trackId: "33333333-3333-4333-8333-3333333333a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 4000,
        speed: 2,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
  ],
);

// ── TEXT OVERLAYS (drawtext parity, Text_Overlay_Export_Spec.md §11.1.5) ────────────
// Six fixtures, one per parity risk, each a BLUE full-frame background (so glyph edges +
// white text + outline contrast strongly → SSIM/PSNR actually exercise the text) with a
// single overlay track on top. These render only on the pinned-FFmpeg image that ALSO
// bundles Inter (the Dockerfile change), since drawtext needs the Inter TTFs. Pixel-
// goldens are generated there via `pnpm generate:fixtures --goldens`; locally (no Inter)
// the gate skips, exactly like the media fixtures.
const TEXT_BG_TRACK = "aaaa0000-0000-4000-8000-0000000000b0";
const TEXT_OVERLAY_TRACK = "aaaa0000-0000-4000-8000-0000000000c0";

/** Full-frame BLUE background clip (0–2000ms) for a text fixture to draw onto. */
function textBgClip(idSuffix: string): Clip {
  return {
    // Stable, valid UUID v4: fixed prefix + a 2-hex-digit suffix per fixture (node = 12 hex).
    id: `aaaa0000-0000-4000-8000-0000000000${idSuffix}`,
    sourceAssetId: ASSET_BLUE,
    trackId: TEXT_BG_TRACK,
    startOnTimeline: 0,
    endOnTimeline: 2000,
    trimIn: 0,
    trimOut: 2000,
    speed: 1,
    effects: [],
    keyframes: {},
    linkedClipId: null,
  };
}

const TEXT_OVERLAY_BASE = {
  trackId: TEXT_OVERLAY_TRACK,
  kind: "text" as const,
  startOnTimeline: 0,
  endOnTimeline: 2000,
  canvasX: 5,
  canvasY: 40,
  width: 90,
  height: 20,
  rotation: 0,
  opacity: 100,
  animation: {},
  keyframes: {},
};

const TEXT_STYLE_BASE: TextStyle = {
  // fontFamily is intentionally "sans-serif" — the export must render Inter (R1).
  fontFamily: "sans-serif",
  fontSize: 48,
  fontWeight: 600,
  color: "#FFFFFF",
  align: "center",
  outline: { color: "#000000", width: 2, position: "outside" },
};

function textOverlay(id: string, text: string, style: Partial<TextStyle>, extra: Partial<TextOverlay> = {}): TextOverlay {
  return {
    ...TEXT_OVERLAY_BASE,
    id,
    text,
    style: { ...TEXT_STYLE_BASE, ...style },
    ...extra,
  };
}

/** A text fixture project: BLUE background video (track 0) + an overlay track (track 1). */
function textProject(id: string, title: string, overlays: TextOverlay[]): Project {
  const p = baseProject(id, title, [videoTrack(TEXT_BG_TRACK, "Background", [textBgClip(id.slice(-2))])]);
  const overlayTrack: OverlayTrack = {
    id: TEXT_OVERLAY_TRACK,
    type: "overlay",
    name: "Overlay 1",
    colour: "#FF7A1A",
    height: 72,
    muted: false,
    solo: false,
    locked: false,
    clips: overlays,
  };
  p.tracks.push(overlayTrack);
  return p;
}

// (1) default — the §1 default overlay; fontFamily "sans-serif" MUST render Inter (R1).
export const overlayTextDefaultProject = textProject(
  "a1111111-1111-4111-8111-111111111111",
  "overlay_text_default",
  [textOverlay("a1111111-1111-4111-8111-1111111111d1", "Hello", {})],
);

// (2) aligns — three overlays at left / center / right, in their respective corners,
//     locking the §5.3 horizontal-anchor expressions in one frame.
export const overlayTextAlignsProject = textProject(
  "a2222222-2222-4222-8222-222222222222",
  "overlay_text_aligns",
  [
    textOverlay("a2222222-2222-4222-8222-2222222222d1", "Left", { align: "left" }, { canvasX: 5, canvasY: 10, width: 90, height: 15 }),
    textOverlay("a2222222-2222-4222-8222-2222222222d2", "Center", { align: "center" }, { canvasX: 5, canvasY: 42, width: 90, height: 15 }),
    textOverlay("a2222222-2222-4222-8222-2222222222d3", "Right", { align: "right" }, { canvasX: 5, canvasY: 74, width: 90, height: 15 }),
  ],
);

// (3) multiline — a 3-line block via "\n"; the block is centred on the box mid-line and
//     line_spacing matches lineHeight (R6 / §6).
export const overlayTextMultilineProject = textProject(
  "a3333333-3333-4333-8333-333333333333",
  "overlay_text_multiline",
  [textOverlay("a3333333-3333-4333-8333-3333333333d1", "Line one\nLine two\nLine three", { fontSize: 36 })],
);

// (4) escape — `:` `'` `%` `\` and quotes; routed through textfile= so the graph never
//     sees the raw text (R3).
export const overlayTextEscapeProject = textProject(
  "a4444444-4444-4444-8444-444444444444",
  "overlay_text_escape",
  [textOverlay("a4444444-4444-4444-8444-4444444444d1", 'He said: "50% off"', { fontSize: 40 })],
);

// (5) subfloor — a tiny fontSize that hits the 12px floor at the 360-tall canvas (R5).
export const overlayTextSubfloorProject = textProject(
  "a5555555-5555-4555-8555-555555555555",
  "overlay_text_subfloor",
  [textOverlay("a5555555-5555-4555-8555-5555555555d1", "tiny floored text", { fontSize: 6 })],
);

// (6) weight_opacity — fontWeight 700 (Inter-Bold, R2), opacity 60, coloured outline; the
//     opacity multiplies both fill and border alpha (§7.2).
export const overlayTextWeightOpacityProject = textProject(
  "a6666666-6666-4666-8666-666666666666",
  "overlay_text_weight_opacity",
  [
    textOverlay(
      "a6666666-6666-4666-8666-6666666666d1",
      "Bold & Faded",
      { fontWeight: 700, color: "#FF7A1A", outline: { color: "#101010", width: 3, position: "outside" } },
      { opacity: 60 },
    ),
  ],
);

/**
 * One fixture-matrix entry. `sampleTimesMs` are timeline timestamps at which a
 * frame is extracted and compared to the committed golden PNG named
 * `<id>_t<ms>.png` under fixtures/golden/.
 */
export interface GoldenFixture {
  id: string;
  project: Project;
  /** Timeline timestamps (ms) to extract+compare. Chosen inside every clip's span. */
  sampleTimesMs: number[];
}

/**
 * The 3-fixture matrix consumed by both golden.test.ts (compare) and
 * generate-fixtures.ts (--update / initial golden synthesis).
 */
export const GOLDEN_FIXTURES: GoldenFixture[] = [
  // Trim: clip spans timeline 0–2000; sample at 1000ms (well inside, avoids edges).
  { id: "trim", project: trimProject, sampleTimesMs: [1000] },
  // Stack: both layers span 0–2000; sample at 1000ms.
  { id: "stack", project: stackProject, sampleTimesMs: [1000] },
  // Speed: 2× clip spans timeline 0–2000; sample at 1000ms (= source t≈2000ms).
  { id: "speed", project: speedProject, sampleTimesMs: [1000] },
  // Text overlays — each samples at 1000ms (strictly inside the [0,2000) window, so the
  // `enable=between` inclusive-end nuance is irrelevant). These render only where Inter is
  // bundled (the pinned-FFmpeg image); the gate skips otherwise (like the media fixtures).
  { id: "overlay_text_default", project: overlayTextDefaultProject, sampleTimesMs: [1000] },
  { id: "overlay_text_aligns", project: overlayTextAlignsProject, sampleTimesMs: [1000] },
  { id: "overlay_text_multiline", project: overlayTextMultilineProject, sampleTimesMs: [1000] },
  { id: "overlay_text_escape", project: overlayTextEscapeProject, sampleTimesMs: [1000] },
  { id: "overlay_text_subfloor", project: overlayTextSubfloorProject, sampleTimesMs: [1000] },
  { id: "overlay_text_weight_opacity", project: overlayTextWeightOpacityProject, sampleTimesMs: [1000] },
];
