// ─────────────────────────────────────────────────────────────────────────────
// Golden-frame fixture PROJECTS (Spec §22.3 / §22.6).
//
// Three minimal §18 `Project` documents, each exercising ONE high-risk graph path
// of buildExportCommand so a golden-frame SSIM/PSNR breach localises to a single
// behaviour:
//
//   (a) "trim"   — per-clip -ss/-to accurate seek from the SOURCE origin (§3.8).
//   (b) "stack"  — multi-track composite + overlay z-order: track 0 (bottom) is
//                  covered by a smaller PiP clip on track 1 (top) (§18.3 z-order).
//   (c) "speed"  — per-clip setpts speed change (2×) (§3.3, §5.1).
//
// Each project references SYNTHETIC fixture media generated by
// scripts/generate-fixtures.ts (lavfi testsrc/colour sources — CC0). The asset ids
// below map to those files via FIXTURE_ASSET_MAP (consumed by golden.test.ts and
// generate-fixtures.ts). All ids are stable UUID-v4 literals so the goldens are
// deterministically tied to a fixed input (the §22.3 precondition).
//
// Geometry is percent (0–100); time is integer ms; track index = z-order. These
// projects are intentionally tiny (single short clips) so a render is sub-second
// and the committed golden PNGs stay small + diff-reviewable (no Git LFS).
// ─────────────────────────────────────────────────────────────────────────────

import type {
  Project,
  VideoTrack,
  AudioTrack,
  CaptionTrack,
  Clip,
  OverlayTrack,
  TextOverlay,
  TextStyle,
} from "@videoforge/project-schema";
import type { ExportSettings } from "@videoforge/ffmpeg-graph";

// ── Stable ids ────────────────────────────────────────────────────────────────
const OWNER_ID = "4f3a6c2e-1b8d-4e2a-9c7f-0a1b2c3d4e5f";
const WORKSPACE_ID = "7c9e6679-7425-40de-944b-e07fc1f90ae7";

// Synthetic source assets (mapped to fixture files in FIXTURE_ASSET_MAP).
export const ASSET_BARS = "aa000000-0000-4000-8000-000000000001"; // testsrc2 counter clip
export const ASSET_RED = "aa000000-0000-4000-8000-000000000002"; // solid red clip
export const ASSET_BLUE = "aa000000-0000-4000-8000-000000000003"; // solid blue clip
// New parity-surface sources.
export const ASSET_GREEN = "aa000000-0000-4000-8000-000000000004"; // solid green clip (linked-audio video bed)
export const ASSET_SQUARE = "aa000000-0000-4000-8000-000000000005"; // 1:1 testsrc2 — non-16:9 → contain bars / cover crop are visible
export const ASSET_TONE_LOUD = "aa000000-0000-4000-8000-000000000006"; // 0 dBFS-ish 440Hz tone WAV — drives volume-envelope + linked audio RMS

/**
 * Asset id → synthetic fixture filename (under fixtures/media/). The render
 * harness substitutes `asset:<id>` tokens with these paths; the generator
 * produces exactly these files. Keeping the map here keeps it single-source.
 */
export const FIXTURE_ASSET_MAP: Record<string, string> = {
  [ASSET_BARS]: "gold_bars_5s.mp4",
  [ASSET_RED]: "gold_red_3s.mp4",
  [ASSET_BLUE]: "gold_blue_3s.mp4",
  [ASSET_GREEN]: "gold_green_3s.mp4",
  [ASSET_SQUARE]: "gold_square_3s.mp4",
  [ASSET_TONE_LOUD]: "gold_tone_3s.wav",
};

// ── Shared export settings (lossy H.264 @ Auto-CRF row of §22.3) ────────────────
// 640×360 keeps goldens tiny; watermark/captions OFF so the gate isolates the
// graph path under test (no font/branding-asset dependence in the golden image).
export const GOLDEN_EXPORT_SETTINGS: ExportSettings = {
  format: "mp4",
  videoCodec: "h264",
  resolution: { w: 640, h: 360 },
  fps: 30,
  crf: 18,
  captions: "none",
  watermark: false,
};

// ── Helpers ─────────────────────────────────────────────────────────────────────
function videoTrack(id: string, name: string, clips: Clip[]): VideoTrack {
  return {
    id,
    type: "video",
    name,
    colour: "#3A6BFF",
    height: 72,
    muted: false,
    solo: false,
    locked: false,
    hidden: false,
    clips,
  };
}

function audioTrack(
  id: string,
  name: string,
  clips: Clip[],
  mix: { volume?: number; pan?: number; volumeEnvelope?: Array<{ timeMs: number; value: number }> } = {},
): AudioTrack {
  return {
    id,
    type: "audio",
    name,
    colour: "#1FB6A0",
    height: 56,
    muted: false,
    solo: false,
    locked: false,
    hidden: false,
    volume: mix.volume ?? 100,
    pan: mix.pan ?? 0,
    volumeEnvelope: mix.volumeEnvelope ?? [],
    clips,
  };
}

function baseProject(id: string, title: string, tracks: Project["tracks"]): Project {
  return {
    schemaVersion: 1,
    revision: 1,
    id,
    title,
    description: `Golden-frame fixture: ${title}`,
    canvas: {
      width: 640,
      height: 360,
      frameRate: 30,
      aspectRatio: "16:9",
      backgroundColor: "#000000",
    },
    tracks,
    captionTracks: [],
    transitions: [],
    markers: [],
    exportPresets: [],
    ownerId: OWNER_ID,
    workspaceId: WORKSPACE_ID,
    collaborators: [{ userId: OWNER_ID, role: "admin" }],
    isPublic: false,
    templateId: null,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z",
  };
}

// ── (a) TRIM ─────────────────────────────────────────────────────────────────────
// One clip from the testsrc counter source, trimmed to source 2000–4000ms. The
// extracted golden frame must show the counter/colour state at SOURCE t=2s+, NOT
// t=0 — proving -ss/-to seeks from the source origin, not the timeline.
export const trimProject: Project = baseProject(
  "11111111-1111-4111-8111-111111111111",
  "trim",
  [
    videoTrack("11111111-1111-4111-8111-1111111111a0", "Video 1", [
      {
        id: "11111111-1111-4111-8111-1111111111c0",
        sourceAssetId: ASSET_BARS,
        trackId: "11111111-1111-4111-8111-1111111111a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 2000,
        trimOut: 4000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
  ],
);

// ── (b) STACK / OVERLAY Z-ORDER ──────────────────────────────────────────────────
// Track 0 (bottom) = full-frame RED. Track 1 (top) = a BLUE PiP box covering the
// centre. The golden must show RED background with a BLUE rectangle ON TOP — if the
// overlay z-order inverts, SSIM collapses (blue would be hidden behind red).
export const stackProject: Project = baseProject(
  "22222222-2222-4222-8222-222222222222",
  "stack",
  [
    // index 0 = bottom layer
    videoTrack("22222222-2222-4222-8222-2222222222a0", "Background", [
      {
        id: "22222222-2222-4222-8222-2222222222c0",
        sourceAssetId: ASSET_RED,
        trackId: "22222222-2222-4222-8222-2222222222a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
    // index 1 = top layer — BLUE centred PiP box (40% size, centred).
    videoTrack("22222222-2222-4222-8222-2222222222a1", "PiP", [
      {
        id: "22222222-2222-4222-8222-2222222222c1",
        sourceAssetId: ASSET_BLUE,
        trackId: "22222222-2222-4222-8222-2222222222a1",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
        transform: { x: 30, y: 30, width: 40, height: 40 },
      },
    ]),
  ],
);

// ── (c) SPEED CHANGE ──────────────────────────────────────────────────────────────
// One clip from the testsrc counter source at 2× speed (setpts=0.5*PTS). A 4s source
// span plays in 2s. The frame sampled at timeline t=1.0s must equal the SOURCE state
// at t=2.0s — proving the setpts time-warp. If speed is ignored, the sampled frame
// shows source t=1.0s and SSIM collapses.
export const speedProject: Project = baseProject(
  "33333333-3333-4333-8333-333333333333",
  "speed",
  [
    videoTrack("33333333-3333-4333-8333-3333333333a0", "Video 1", [
      {
        id: "33333333-3333-4333-8333-3333333333c0",
        sourceAssetId: ASSET_BARS,
        trackId: "33333333-3333-4333-8333-3333333333a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 4000,
        speed: 2,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
  ],
);

// ── TEXT OVERLAYS (drawtext parity, Text_Overlay_Export_Spec.md §11.1.5) ────────────
// Six fixtures, one per parity risk, each a BLUE full-frame background (so glyph edges +
// white text + outline contrast strongly → SSIM/PSNR actually exercise the text) with a
// single overlay track on top. These render only on the pinned-FFmpeg image that ALSO
// bundles Inter (the Dockerfile change), since drawtext needs the Inter TTFs. Pixel-
// goldens are generated there via `pnpm generate:fixtures --goldens`; locally (no Inter)
// the gate skips, exactly like the media fixtures.
const TEXT_BG_TRACK = "aaaa0000-0000-4000-8000-0000000000b0";
const TEXT_OVERLAY_TRACK = "aaaa0000-0000-4000-8000-0000000000c0";

/** Full-frame BLUE background clip (0–2000ms) for a text fixture to draw onto. */
function textBgClip(idSuffix: string): Clip {
  return {
    // Stable, valid UUID v4: fixed prefix + a 2-hex-digit suffix per fixture (node = 12 hex).
    id: `aaaa0000-0000-4000-8000-0000000000${idSuffix}`,
    sourceAssetId: ASSET_BLUE,
    trackId: TEXT_BG_TRACK,
    startOnTimeline: 0,
    endOnTimeline: 2000,
    trimIn: 0,
    trimOut: 2000,
    speed: 1,
    effects: [],
    keyframes: {},
    linkedClipId: null,
  };
}

const TEXT_OVERLAY_BASE = {
  trackId: TEXT_OVERLAY_TRACK,
  kind: "text" as const,
  startOnTimeline: 0,
  endOnTimeline: 2000,
  canvasX: 5,
  canvasY: 40,
  width: 90,
  height: 20,
  rotation: 0,
  opacity: 100,
  animation: {},
  keyframes: {},
};

const TEXT_STYLE_BASE: TextStyle = {
  // fontFamily is intentionally "sans-serif" — the export must render Inter (R1).
  fontFamily: "sans-serif",
  fontSize: 48,
  fontWeight: 600,
  color: "#FFFFFF",
  align: "center",
  outline: { color: "#000000", width: 2, position: "outside" },
};

function textOverlay(id: string, text: string, style: Partial<TextStyle>, extra: Partial<TextOverlay> = {}): TextOverlay {
  return {
    ...TEXT_OVERLAY_BASE,
    id,
    text,
    style: { ...TEXT_STYLE_BASE, ...style },
    ...extra,
  };
}

/** A text fixture project: BLUE background video (track 0) + an overlay track (track 1). */
function textProject(id: string, title: string, overlays: TextOverlay[]): Project {
  const p = baseProject(id, title, [videoTrack(TEXT_BG_TRACK, "Background", [textBgClip(id.slice(-2))])]);
  const overlayTrack: OverlayTrack = {
    id: TEXT_OVERLAY_TRACK,
    type: "overlay",
    name: "Overlay 1",
    colour: "#FF7A1A",
    height: 72,
    muted: false,
    solo: false,
    locked: false,
    hidden: false,
    clips: overlays,
  };
  p.tracks.push(overlayTrack);
  return p;
}

// (1) default — the §1 default overlay; fontFamily "sans-serif" MUST render Inter (R1).
export const overlayTextDefaultProject = textProject(
  "a1111111-1111-4111-8111-111111111111",
  "overlay_text_default",
  [textOverlay("a1111111-1111-4111-8111-1111111111d1", "Hello", {})],
);

// (2) aligns — three overlays at left / center / right, in their respective corners,
//     locking the §5.3 horizontal-anchor expressions in one frame.
export const overlayTextAlignsProject = textProject(
  "a2222222-2222-4222-8222-222222222222",
  "overlay_text_aligns",
  [
    textOverlay("a2222222-2222-4222-8222-2222222222d1", "Left", { align: "left" }, { canvasX: 5, canvasY: 10, width: 90, height: 15 }),
    textOverlay("a2222222-2222-4222-8222-2222222222d2", "Center", { align: "center" }, { canvasX: 5, canvasY: 42, width: 90, height: 15 }),
    textOverlay("a2222222-2222-4222-8222-2222222222d3", "Right", { align: "right" }, { canvasX: 5, canvasY: 74, width: 90, height: 15 }),
  ],
);

// (3) multiline — a 3-line block via "\n"; the block is centred on the box mid-line and
//     line_spacing matches lineHeight (R6 / §6).
export const overlayTextMultilineProject = textProject(
  "a3333333-3333-4333-8333-333333333333",
  "overlay_text_multiline",
  [textOverlay("a3333333-3333-4333-8333-3333333333d1", "Line one\nLine two\nLine three", { fontSize: 36 })],
);

// (4) escape — `:` `'` `%` `\` and quotes; routed through textfile= so the graph never
//     sees the raw text (R3).
export const overlayTextEscapeProject = textProject(
  "a4444444-4444-4444-8444-444444444444",
  "overlay_text_escape",
  [textOverlay("a4444444-4444-4444-8444-4444444444d1", 'He said: "50% off"', { fontSize: 40 })],
);

// (5) subfloor — a tiny fontSize that hits the 12px floor at the 360-tall canvas (R5).
export const overlayTextSubfloorProject = textProject(
  "a5555555-5555-4555-8555-555555555555",
  "overlay_text_subfloor",
  [textOverlay("a5555555-5555-4555-8555-5555555555d1", "tiny floored text", { fontSize: 6 })],
);

// (6) weight_opacity — fontWeight 700 (Inter-Bold, R2), opacity 60, coloured outline; the
//     opacity multiplies both fill and border alpha (§7.2).
export const overlayTextWeightOpacityProject = textProject(
  "a6666666-6666-4666-8666-666666666666",
  "overlay_text_weight_opacity",
  [
    textOverlay(
      "a6666666-6666-4666-8666-6666666666d1",
      "Bold & Faded",
      { fontWeight: 700, color: "#FF7A1A", outline: { color: "#101010", width: 3, position: "outside" } },
      { opacity: 60 },
    ),
  ],
);

// ── (k) CAPTION-TYPEWRITER (character-by-character reveal parity) ───────────────────
// The big-caption typewriter feature (Script Studio): a TextOverlay whose
// `animation.typewriter.words[]` drives a per-character reveal. The SHARED
// getRevealedPrefix/getCharRevealSteps helper computes the revealed prefix for BOTH
// the preview canvas AND the exporter's per-step `drawtext enable=between(...)` stages,
// so the partially-revealed caption is frame-identical in both (WYCIWYG; DECISIONS
// 2026-06-27). Two cases, each sampled at a MID-reveal time so the golden captures a
// genuine PARTIAL prefix (not the trivially-equal empty/full ends):
//   (a) char-level, EVEN distribution: one word window over the whole string, so each
//       character reveals at start + span*c/len. At t=1000ms (mid the 0–2000 window) a
//       ~half prefix is shown — the even-distribution timing the helper synthesises.
//   (b) word-timed, REAL Script Studio words[]: three words with distinct windows; at
//       t=1100ms the first two words + the leading chars of the third are revealed.
// Inter-dependent (drawtext), like the other text fixtures: renders only on the pinned
// image that bundles Inter; the gate skips locally exactly as for overlay_text_*.
const TW_CHAR_TEXT = "TYPEWRITER"; // 10 chars, one even-distributed word window
export const captionTypewriterCharProject = textProject(
  "ab111111-1111-4111-8111-111111111111",
  "caption_typewriter_char",
  [
    textOverlay(
      "ab111111-1111-4111-8111-1111111111d1",
      TW_CHAR_TEXT,
      { fontSize: 56, align: "center" },
      {
        canvasX: 5,
        canvasY: 70, // lower-third, like the Script Studio big caption
        width: 90,
        height: 20,
        animation: {
          typewriter: {
            // Single word window spanning the overlay → even per-char distribution.
            words: [{ text: TW_CHAR_TEXT, startMs: 0, endMs: 2000 }],
          },
        },
      },
    ),
  ],
);

// Real Script Studio words[]: each word has its own [startMs,endMs) window (the
// even-distributed VO timing assemblePlanned emits). Chars within a word spread evenly
// across that word's window; the space before a word reveals with that word's first char.
const TW_WORD_TEXT = "Make it pop";
export const captionTypewriterWordProject = textProject(
  "ab222222-2222-4222-8222-222222222222",
  "caption_typewriter_word",
  [
    textOverlay(
      "ab222222-2222-4222-8222-2222222222d1",
      TW_WORD_TEXT,
      { fontSize: 56, align: "center" },
      {
        canvasX: 5,
        canvasY: 70,
        width: 90,
        height: 20,
        animation: {
          typewriter: {
            words: [
              { text: "Make", startMs: 0, endMs: 700 },
              { text: "it", startMs: 700, endMs: 1100 },
              { text: "pop", startMs: 1100, endMs: 2000 },
            ],
          },
        },
      },
    ),
  ],
);

// ── (d) SPLIT ─────────────────────────────────────────────────────────────────────
// One source split into TWO adjacent timeline clips at the cut point. Clip A plays
// source 0–1000ms on timeline 0–1000; clip B plays source 1000–2000ms on timeline
// 1000–2000. Sampling at 500ms (inside A) and 1500ms (inside B) proves each half
// shows its OWN source span — i.e. the split's trim bookkeeping is correct and the
// two clips don't both replay source-origin frames.
export const splitProject: Project = baseProject(
  "44444444-4444-4444-8444-444444444444",
  "split",
  [
    videoTrack("44444444-4444-4444-8444-4444444444a0", "Video 1", [
      {
        id: "44444444-4444-4444-8444-4444444444c0",
        sourceAssetId: ASSET_BARS,
        trackId: "44444444-4444-4444-8444-4444444444a0",
        startOnTimeline: 0,
        endOnTimeline: 1000,
        trimIn: 0,
        trimOut: 1000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
      {
        id: "44444444-4444-4444-8444-4444444444c1",
        sourceAssetId: ASSET_BARS,
        trackId: "44444444-4444-4444-8444-4444444444a0",
        startOnTimeline: 1000,
        endOnTimeline: 2000,
        trimIn: 1000,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
  ],
);

// ── (e) LINKED-AUDIO MOVE ───────────────────────────────────────────────────────────
// A video clip + its linked audio clip, both MOVED to start at timeline 1000ms (the
// link kept them together). The GREEN video bed only appears from 1000ms (before that
// the canvas background shows), and the linked TONE audio only sounds from 1000ms.
//   • video frame @1500ms → GREEN (clip present); @500ms → background (clip absent).
//   • audio RMS @1500ms → loud (tone present); @250ms → ~silent (tone absent).
// This guards that a linked pair exports at the SAME moved position on both streams.
const LINKED_VIDEO_CLIP = "55555555-5555-4555-8555-5555555555c0";
const LINKED_AUDIO_CLIP = "55555555-5555-4555-8555-5555555555c1";
export const linkedAudioMoveProject: Project = baseProject(
  "55555555-5555-4555-8555-555555555555",
  "linked_audio_move",
  [
    videoTrack("55555555-5555-4555-8555-5555555555a0", "Video 1", [
      {
        id: LINKED_VIDEO_CLIP,
        sourceAssetId: ASSET_GREEN,
        trackId: "55555555-5555-4555-8555-5555555555a0",
        startOnTimeline: 1000,
        endOnTimeline: 3000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: LINKED_AUDIO_CLIP,
      },
    ]),
    audioTrack("55555555-5555-4555-8555-5555555555b0", "Audio 1", [
      {
        id: LINKED_AUDIO_CLIP,
        sourceAssetId: ASSET_TONE_LOUD,
        trackId: "55555555-5555-4555-8555-5555555555b0",
        startOnTimeline: 1000,
        endOnTimeline: 3000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: LINKED_VIDEO_CLIP,
      },
    ]),
  ],
);

// ── (f) UNDERLINE DRAWBOX ───────────────────────────────────────────────────────────
// A text overlay with `style.underline` → drawtext + a `drawbox` rule under the line
// (drawtext has no underline; the SHARED `underlineRule` geometry is drawn as a filled
// box). If the underline box is mis-placed/sized vs the committed golden, SSIM drops.
export const overlayUnderlineProject = textProject(
  "a7777777-7777-4777-8777-777777777777",
  "overlay_underline",
  [
    textOverlay(
      "a7777777-7777-4777-8777-7777777777d1",
      "Underlined",
      { fontSize: 44, underline: true },
    ),
  ],
);

// ── (g) CAPTION FORCE_STYLE BURN-IN ───────────────────────────────────────────────────
// captions:"burn" → the `subtitles` filter with a `force_style` derived from the track
// CaptionStyle (Inter, scaled size, colour, outline, position). Guards that the burned
// caption matches the preview styling, not libass defaults. Needs Inter (fontconfig) in
// the pinned image — skips locally like the text fixtures.
const CAPTION_BG_TRACK = "66666666-6666-4666-8666-6666666666a0";
const CAPTION_TRACK = "66666666-6666-4666-8666-6666666666f0";
export const captionBurnProject: Project = (() => {
  const p = baseProject(
    "66666666-6666-4666-8666-666666666666",
    "caption_burn",
    [
      videoTrack(CAPTION_BG_TRACK, "Background", [
        {
          id: "66666666-6666-4666-8666-6666666666c0",
          sourceAssetId: ASSET_BLUE,
          trackId: CAPTION_BG_TRACK,
          startOnTimeline: 0,
          endOnTimeline: 2000,
          trimIn: 0,
          trimOut: 2000,
          speed: 1,
          effects: [],
          keyframes: {},
          linkedClipId: null,
        },
      ]),
    ],
  );
  const captionTrack: CaptionTrack = {
    id: CAPTION_TRACK,
    type: "caption",
    name: "Captions",
    colour: "#FFD166",
    height: 48,
    muted: false,
    solo: false,
    locked: false,
    hidden: false,
    language: "en",
    style: {
      fontFamily: "Inter",
      fontSize: 40,
      color: "#FFD166",
      position: "bottom",
      align: "center",
      outline: { width: 3, color: "#101010" },
    },
    blocks: [
      {
        id: "66666666-6666-4666-8666-6666666666b1",
        startMs: 0,
        endMs: 2000,
        text: "Burned caption",
      },
    ],
  };
  p.captionTracks = [captionTrack];
  return p;
})();

// ── (h) WATERMARK-OFF DEFAULT ─────────────────────────────────────────────────────────
// 2026-06-14 decision: watermark is OFF by default (watermark-free 1080p). This fixture
// renders a full-frame RED clip with watermark:false (the default settings) and asserts
// the bottom-right corner is CLEAN red — NO branding badge. A regression that re-enables
// the watermark would stamp a badge in the corner → SSIM drops vs the clean golden.
export const watermarkOffProject: Project = baseProject(
  "77777777-7777-4777-8777-777777777777",
  "watermark_off",
  [
    videoTrack("77777777-7777-4777-8777-7777777777a0", "Video 1", [
      {
        id: "77777777-7777-4777-8777-7777777777c0",
        sourceAssetId: ASSET_RED,
        trackId: "77777777-7777-4777-8777-7777777777a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
  ],
);

// ── (i) IMAGE-CLIP FIT: contain + cover ────────────────────────────────────────────────
// A 1:1 (square) source placed in a WIDE 16:9 box (transform 10..90% × 30..70%). The fit
// mode drives `clipFitScaleSteps`:
//   • contain → letterbox: the square is scaled to fit INSIDE the box, transparent bars
//               left/right reveal the canvas background under it.
//   • cover   → crop: the square is scaled to FILL the box, top/bottom of the source
//               cropped away (no bars).
// Same source + same box, different fit → visibly different frames; each has its own
// golden, guarding the SHARED contain/cover geometry. (The builder treats image and
// video clips identically — same `asset:` input — so a video square exercises the exact
// image-fit code path deterministically without an opaque PNG binary input.)
const FIT_BOX = { x: 10, y: 30, width: 80, height: 40 }; // wide box; source is square → AR mismatch
function fitProject(id: string, title: string, fit: "contain" | "cover", clipId: string): Project {
  return baseProject(id, title, [
    // Bottom: full-frame RED so contain's transparent letterbox bars are clearly red.
    videoTrack(`${id.slice(0, 8)}-0000-4000-8000-0000000000a0`, "Background", [
      {
        id: `${id.slice(0, 8)}-0000-4000-8000-0000000000c9`,
        sourceAssetId: ASSET_RED,
        trackId: `${id.slice(0, 8)}-0000-4000-8000-0000000000a0`,
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
    // Top: the square source in the wide box, with the fit under test.
    videoTrack(`${id.slice(0, 8)}-0000-4000-8000-0000000000a1`, "Image", [
      {
        id: clipId,
        sourceAssetId: ASSET_SQUARE,
        trackId: `${id.slice(0, 8)}-0000-4000-8000-0000000000a1`,
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
        transform: FIT_BOX,
        fit,
      },
    ]),
  ]);
}
export const imageContainProject = fitProject(
  "88888888-8888-4888-8888-888888888888",
  "image_contain",
  "contain",
  "88888888-8888-4888-8888-8888888888c1",
);
export const imageCoverProject = fitProject(
  "99999999-9999-4999-8999-999999999999",
  "image_cover",
  "cover",
  "99999999-9999-4999-8999-9999999999c1",
);

// ── (j) VOLUME-ENVELOPE (audio parity via RMS) ──────────────────────────────────────────
// An audio track carrying the loud tone, with a piecewise-LINEAR volume envelope that
// ramps the gain from ~0% at t=0 up to 100% at t=2000ms (the §3.4 automation). Frame
// SSIM doesn't apply to audio, so this fixture is checked via RMS energy at two times:
//   • @250ms  → low RMS (envelope near the bottom of the ramp).
//   • @1800ms → high RMS (envelope near the top of the ramp).
// The asserted RATIO (later >> earlier) proves the export reproduced the SAME automation
// curve the preview mix samples — the audio half of the WYCIWYG invariant.
export const audioVolumeEnvelopeProject: Project = baseProject(
  "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  "audio_volume_envelope",
  [
    // A 1px video bed so the export has a video stream too (keeps the encode well-formed).
    videoTrack("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa0a0", "Video 1", [
      {
        id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa0c0",
        sourceAssetId: ASSET_BLUE,
        trackId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa0a0",
        startOnTimeline: 0,
        endOnTimeline: 2000,
        trimIn: 0,
        trimOut: 2000,
        speed: 1,
        effects: [],
        keyframes: {},
        linkedClipId: null,
      },
    ]),
    audioTrack(
      "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa0b0",
      "Audio 1",
      [
        {
          id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa0c1",
          sourceAssetId: ASSET_TONE_LOUD,
          trackId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaa0b0",
          startOnTimeline: 0,
          endOnTimeline: 2000,
          trimIn: 0,
          trimOut: 2000,
          speed: 1,
          effects: [],
          keyframes: {},
          linkedClipId: null,
        },
      ],
      // Linear ramp 0% → 100% across the 2s span.
      { volumeEnvelope: [{ timeMs: 0, value: 0 }, { timeMs: 2000, value: 100 }] },
    ),
  ],
);

/**
 * What a fixture's render is compared on:
 *   • "frame"     — extract PNG(s) at sampleTimesMs and SSIM/PSNR vs committed goldens.
 *   • "audio-rms" — extract per-window RMS at audioWindowsMs and assert a gain RATIO
 *                   (audio has no frame golden; we check the envelope SHAPE, not a PNG).
 */
export type GoldenCompare = "frame" | "audio-rms";

/**
 * One fixture-matrix entry. `sampleTimesMs` are timeline timestamps at which a
 * frame is extracted and compared to the committed golden PNG named
 * `<id>_t<ms>.png` under fixtures/golden/.
 */
export interface GoldenFixture {
  id: string;
  project: Project;
  /** How this fixture is verified. Defaults to "frame". */
  compare?: GoldenCompare;
  /** Per-fixture export-settings override (merged over GOLDEN_EXPORT_SETTINGS). */
  settings?: Partial<ExportSettings>;
  /** Timeline timestamps (ms) to extract+compare. Chosen inside every clip's span. */
  sampleTimesMs: number[];
  /**
   * For compare:"audio-rms" — ordered analysis windows. Each is a short span over which
   * mean-volume RMS (dBFS) is measured. The test asserts the LAST window is louder than
   * the FIRST by at least `minRmsGainDb`, proving the gain automation/placement.
   */
  audioWindowsMs?: Array<{ startMs: number; durMs: number }>;
  /** For compare:"audio-rms" — required dB gain from the first to the last window. */
  minRmsGainDb?: number;
}

/**
 * The 3-fixture matrix consumed by both golden.test.ts (compare) and
 * generate-fixtures.ts (--update / initial golden synthesis).
 */
export const GOLDEN_FIXTURES: GoldenFixture[] = [
  // ── Spec-set core graph paths ──────────────────────────────────────────────────
  // Trim: clip spans timeline 0–2000; sample at 1000ms (well inside, avoids edges).
  { id: "trim", project: trimProject, sampleTimesMs: [1000] },
  // Split: two adjacent halves; sample inside EACH (500ms = clip A, 1500ms = clip B).
  { id: "split", project: splitProject, sampleTimesMs: [500, 1500] },
  // Stack: both layers span 0–2000; sample at 1000ms.
  { id: "stack", project: stackProject, sampleTimesMs: [1000] },
  // Speed: 2× clip spans timeline 0–2000; sample at 1000ms (= source t≈2000ms).
  { id: "speed", project: speedProject, sampleTimesMs: [1000] },
  // Linked-audio move: pair moved to start @1000ms. @1500ms GREEN bed is present,
  // @500ms it is not (background). (Audio side of the link is covered by RMS below.)
  { id: "linked_audio_move", project: linkedAudioMoveProject, sampleTimesMs: [500, 1500] },

  // ── This session's new parity surfaces (each guards one) ─────────────────────────
  // Watermark-OFF default (2026-06-14): clean corner, no branding badge.
  { id: "watermark_off", project: watermarkOffProject, sampleTimesMs: [1000] },
  // Image-clip fit: same square source + same wide box, contain vs cover.
  { id: "image_contain", project: imageContainProject, sampleTimesMs: [1000] },
  { id: "image_cover", project: imageCoverProject, sampleTimesMs: [1000] },

  // ── Text overlays — each samples at 1000ms (strictly inside the [0,2000) window, so the
  // `enable=between` inclusive-end nuance is irrelevant). These render only where Inter is
  // bundled (the pinned-FFmpeg image); the gate skips otherwise (like the media fixtures).
  { id: "overlay_text_default", project: overlayTextDefaultProject, sampleTimesMs: [1000] },
  { id: "overlay_text_aligns", project: overlayTextAlignsProject, sampleTimesMs: [1000] },
  { id: "overlay_text_multiline", project: overlayTextMultilineProject, sampleTimesMs: [1000] },
  { id: "overlay_text_escape", project: overlayTextEscapeProject, sampleTimesMs: [1000] },
  { id: "overlay_text_subfloor", project: overlayTextSubfloorProject, sampleTimesMs: [1000] },
  { id: "overlay_text_weight_opacity", project: overlayTextWeightOpacityProject, sampleTimesMs: [1000] },
  // Underline → drawtext + drawbox rule (Inter-dependent, like text fixtures).
  { id: "overlay_underline", project: overlayUnderlineProject, sampleTimesMs: [1000] },
  // Caption force_style burn-in (Inter via fontconfig in the pinned image).
  { id: "caption_burn", project: captionBurnProject, settings: { captions: "burn" }, sampleTimesMs: [1000] },

  // ── Caption typewriter (character-by-character reveal) — sampled MID-reveal so the
  // golden captures a genuine partial prefix. The SHARED getCharRevealSteps drives the
  // per-step drawtext enable=between(...) stages; preview's getRevealedPrefix returns the
  // SAME prefix at the SAME playhead → frame-identical. Inter-dependent like text fixtures.
  //   (a) char-level even-distribution: "TYPEWRITER" over 0–2000ms; @1000ms ⇒ "TYPEWR".
  { id: "caption_typewriter_char", project: captionTypewriterCharProject, sampleTimesMs: [1000] },
  //   (b) word-timed from real words[]: "Make it pop"; @1100ms ⇒ "Make it p".
  { id: "caption_typewriter_word", project: captionTypewriterWordProject, sampleTimesMs: [1100] },

  // ── Audio parity (RMS, not frame SSIM) ──────────────────────────────────────────
  // Volume envelope: gain ramps 0%→100% over 2s; later window must be much louder.
  {
    id: "audio_volume_envelope",
    project: audioVolumeEnvelopeProject,
    compare: "audio-rms",
    sampleTimesMs: [],
    audioWindowsMs: [
      { startMs: 100, durMs: 300 },
      { startMs: 1600, durMs: 300 },
    ],
    minRmsGainDb: 12,
  },
];
